<a href="https://colab.research.google.com/github/kovacova/random-magic/blob/master/projects/07_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [3]:
a = np.mat('4 3 ; 2 1')
a

matrix([[4, 3],
        [2, 1]])

In [6]:
print('Transpose \n', a.T)

Transpose 
 [[4 2]
 [3 1]]


In [7]:
print('Inverse \n', a.I)

Inverse 
 [[-0.5  1.5]
 [ 1.  -2. ]]


# Numpy Linalg - Linear Algebra Library for Numpy

In [0]:
# Numpy Linalg - Linear Algebra Library for Numpy

c = np.asmatrix(df['column_1', 'column_2'])